config/routes.rb
Rails.application.routes.draw do
  root "home#index"

  get "home/index"
  get "users/index"
  get "users/show"
  get "users/new"
  get "users/edit"
  get "users/delete"
  get "users/login"
  get "users/attempt_logout", to: "users#attempt_logout"
  
  post "users/create"
  post "users/attempt_login", to: "users#attempt_login"
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
  has_one_attached :pic
  has_one_attached :document
  has_many_attached :videos
  has_secure_password

  def pic_resize(x, y)
    x = x.to_i
    y = y.to_i
    # puts "\n\n ***Converted x: #{x}, Converted y: #{y}" # Debugging line

    pic.variant(resize_to_limit: [x, y])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    current_user.present?
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @user = current_user
    if @user
      session[:user_name] = @user.name
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  layout "application"
  def index
    @user = Users.all
  end

  def show
    if session[:user_id]
      @user = User.find(session[:user_id])
    else
      redirect_to root_path
    end
  end

  def new
    @user = User.new
  end

  def edit
  end

  def create
    @user = User.new(user_params)
    @user.last_login = Time.now
    if @user.save
      session[:user_id] = @user.id
      session[:user_name] = @user.name
      redirect_to users_show_path, notice: "User created successfully"
    else
      render :new
    end
  end
  
  def delete
  end

  def login
  end

  def attempt_login
    @user = User.find_by(email: params[:email])
    if @user && @user.authenticate(params[:password])
      @user.update(last_login: Time.now + 6.hours)
      session[:user_id] = @user.id
      session[:user_name] = @user.name
      redirect_to users_show_path, notice: "Logged in successfully!"
    else
      flash.now[:alert] = "Invalid email or password!"
      # Rails.logger.debug "\nFlash alert: #{flash.now[:alert]}\n" # Debug the flash message

      # In Rails 7 turbo expects POST / PUT / PATCH form submissions to redirect, 
      # usually that's create and update controller actions.
      # To render a template, the response has to have an invalid status, like :unprocessable_entity, 
      # otherwise turbo shows an error in the browser console:
      # render :login
      render :login, status: :unprocessable_entity
    end
  end
  def attempt_logout
    params[:id] = nil
    session[:user_id] = nil
    redirect_to root_path, notice: "Logged out successfully"
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :pic, :document, :last_login, videos: [])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<div class="center">
    <h1>Home Page</h1>

    <div>
        <% if logged_in? %>
            <b>Username: <%= session[:user_name] %></b>
            <div> <%= link_to "Logout", users_attempt_logout_path %> </div>
        <% else %>
            <%= link_to "Signup", users_new_path %> | 
            <%= link_to "Login", users_login_path %>
        <% end %>
    </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Active Storage App" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <!-- <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %> -->
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track": "reload" %>

    
    <%= javascript_importmap_tags %>

    <style>
      .center {
        margin: auto;
        width: 50%;
        /* border: 3px solid green; */
        padding: 10px;
        line-height: 30px;
      }

      #togglePassword {
        float: right;
        margin-top: -33px;
        margin-right: 15px;
      }
    </style>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <div class="center">

      <div id="flash-message">
        <% if flash[:notice] %>
          <p class="alert alert-primary">
            <%= flash[:notice] %>
          </p>
        <% end %> 

        <% if flash[:alert] %>
          <p class="alert alert-danger">
            <%= flash[:alert] %>
          </p>
        <% end %> 
      </div>
      

      <b> <%= link_to "Home", root_path %> &nbsp; &nbsp; </b>
      <% if logged_in? %>
        <b> <%= link_to "User Profile", users_show_path %> &nbsp; &nbsp; </b>
        <b> <%= link_to "Logout", users_attempt_logout_path %> &nbsp; &nbsp; </b>
      <% end %>
      
    </div>
    <%= yield %>

    <script>
      document.addEventListener('DOMContentLoaded', function() {
        const flashMessage = document.getElementById('flash-message');
        
        if (flashMessage) {
          setTimeout(function() {
            flashMessage.style.display = 'none';
          }, 1000); // 5000 milliseconds = 5 seconds
        }
      });
    </script>

  </body>
</html>

app/views/users/create.html.erb
<h1>create</h1>

app/views/users/delete.html.erb
<h1>Users#delete</h1>
<p>Find me in app/views/users/delete.html.erb</p>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/index.html.erb
<div class="center">
    <h1>Users#index</h1>
    <p>Find me in app/views/users/index.html.erb</p>
</div>

app/views/users/login.html.erb
<div class="center">
    <h1>Login</h1>
    <%= form_with url: users_attempt_login_path, method: :post, local: true, class: "form-horizontal" do |f| %>
        <div class="mb-3">
            <%= f.label :email, "Email" %>
            <%= f.email_field :email, value: params[:email], class: "form-control" %>
        </div>

        <div class="mb-3">
            <%= f.label :password, "Password" %>
            <%= f.password_field :password, value: params[:password], class: "form-control", id: "password_field" %>
            <i class="bi bi-eye-slash" id="togglePassword"></i>
            <!-- <%= check_box_tag "show_password", "1", false, id: "show_password" %>
            <%= label_tag "show_password", "Show Password" %> -->
        </div>

        <div class="mb-3">
            <div class="d-grid gap-2">
                <%= f.submit "Login", class: "btn btn-primary" %>
            </div>
        </div>
    <% end %>
</div>

<script>
    document.addEventListener('DOMContentLoaded', function() {
        const showPasswordCheckbox = document.getElementById('show_password');
        const passwordField = document.getElementById('password_field');

        showPasswordCheckbox.addEventListener('change', function() {
            // Toggle the type of the password field
            passwordField.type = this.checked ? 'text' : 'password';
        });
    });

    const togglePassword = document.querySelector("#togglePassword");
    const password = document.querySelector("#password_field");
    togglePassword.addEventListener("click", (e) => {
        const type = password.getAttribute("type") === "password" ? "text" : "password";
        password.setAttribute("type", type);
        e.target.classList.toggle("bi-eye");
    });
</script>

app/views/users/new.html.erb
<div class="center">
    <h1>Signup</h1>
    <div>
        <%= form_with model: @user, url: users_create_path, method: :post, 
            local: true, class: "form-horizontal" do |f| %>
            <div class="mb-3">
                <%= f.label :name, "Name" %>
                <%= f.text_field :name, class: "form-control" %>
            </div>
            <div class="mb-3">
                <%= f.label :email, "Email" %>
                <%= f.email_field :email, class: "form-control" %>
            </div>
            <div class="mb-3">
                <%= f.label :password, "Password" %>
                <%= f.password_field :password, class: "form-control" %>
            </div>

            <div class="mb-3">
                <%= f.label :pic, "Profile Picture" %>
                <%= f.file_field :pic, accept: "image/*", class: "form-control" %>
            </div>

            <div class="mb-3">
                <%= f.label :document, "CV" %>
                <%= f.file_field :document, accept: ".pdf,.doc,.docx", class: "form-control" %>
            </div>
            
            <div class="mb-3">
                <%= f.label :videos, "Videos" %>
                <%= f.file_field :videos, multiple: true, accept: "video/*", class: "form-control" %>
            </div>

            <div class="mb-3">
                <div class="d-grid gap-2">
                    <%= f.submit "Submit", disable_with: 'Submiting...', class: "btn btn-outline-success" %>
                </div>
            </div>
        <% end %>
        
    </div>
</div>

app/views/users/show.html.erb
<div class="center content">
    <h1>User Profile</h1>
    <p>
        <% if @user.pic.attached? %>
            <!-- <img src="<%= url_for(@user.pic) %>" alt="" style="width: 200px; height: 200px;"> -->
            <%= image_tag @user.pic_resize(100,100) %>
        <% else %>
            No profile picture available.
        <% end %>
    </p>
    <p> Name: <%= @user.name %> </p> 
    <p> Email: <%= @user.email %> </p>
    <p>
        <p>
            CV:
            <% if @user.document.attached? %>
                <% if @user.document.content_type == "application/pdf" %>
                    <embed src="<%= url_for(@user.document)%>" type="" width="400" height="400">
                <% else %>
                    <%= link_to "Download CV", url_for(@user.document), target: "_blank" %>
                <% end %>
            <% end %>
            
        </p>
    </p>
    <p>
        <p>Videos:</p> 
        <% if @user.videos.attached? %>
            <% @user.videos.each do |video| %>
                <%= video_tag video, controls: true, width: 400 %>
            <% end %>
        <% else %>
            <p>No videos uploaded.</p>
        <% end %>
    </p>

    <p>
        Last login: <%= @user.last_login %>
    </p>
</div>